name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Gets the latest code from GitHub

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/static-website:${{ github.sha }}

  update-k8s-manifests:
    name: Update Kubernetes Manifests
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Image Tag in Kubernetes Manifests
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/static-website:${{ github.sha }}|" k8s-manifests/deployment.yaml

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/nirav2292001/staticweb.git
          git add k8s-manifests/deployment.yaml
          git commit -m "Update deployment image to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
